import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: '#f8f9fa' 
  },
  /* Welcome Modal */
  welcomeModalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)', 
  },
  welcomeModal: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 25,
    marginHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
    width: '90%', 
  },
  welcomeModalTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 15,
    color: '#2A5B8C',
    textAlign: 'center',
  },
  welcomeModalText: {
    fontSize: 16,
    lineHeight: 22,
    color: '#333',
    marginBottom: 20,
    textAlign: 'center',
  },
  welcomeModalButton: {
    backgroundColor: '#2A5B8C',
    paddingVertical: 12,
    borderRadius: 8,
  },

  welcomeModalButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
    textAlign: 'center',
  },
  /* Weather Banner */
  weatherBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    margin: 15,
    marginBottom: 10,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  weatherSunny: {
    backgroundColor: '#FFF9C4',
    borderLeftWidth: 4,
    borderLeftColor: '#FFD600',
  },
  weatherRainy: {
    backgroundColor: '#E3F2FD',
    borderLeftWidth: 4,
    borderLeftColor: '#2196F3',
  },
  weatherStormy: {
    backgroundColor: '#FCE4EC',
    borderLeftWidth: 4,
    borderLeftColor: '#E91E63,'
  },
  weatherDefault: {
    backgroundColor: '#F5F5F5',
    borderLeftWidth: 4,
    borderLeftColor: '#9E9E9E,'
  },
  weatherIcon: {
    fontSize: 24,
    marginRight: 12,
  },
  weatherInfo: {
    flex: 1,
  },
  weatherTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 2,
  },
  weatherMessage: {
    fontSize: 12,
    color: '#666',
    lineHeight: 16,
  },

  /* Create Post Section */
  createPostSection: {
    backgroundColor: 'white',
    margin: 15,
    marginTop: 5,
    marginBottom: 10,
    padding: 15,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 1,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 15,
    marginBottom: 10,
  },
  sectionTitle: { 
    fontSize: 18, 
    fontWeight: '700', 
    color: '#333',
    marginBottom: 10,
  },
  postCount: {
    fontSize: 12,
    color: '#666',
    fontWeight: '500',
  },

  /* Quick Actions / Post Input */
  quickActions: { 
    flexDirection: 'row', 
    alignItems: 'flex-start',
  },
  postInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 10,
    fontSize: 14,
    backgroundColor: 'white',
    color: '#333',
    maxHeight: 80,
    textAlignVertical: 'top',
  },
  sendButton: { 
    marginLeft: 10, 
    backgroundColor: '#2A5B8C', 
    padding: 10, 
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
  },
communityWelcome: {
  backgroundColor: '#E3F2FD',
  padding: 15,
  borderRadius: 12,
  margin: 15,
  marginBottom: 10,
},
welcomeTitle: {
  fontSize: 18,
  fontWeight: '700',
  color: '#1976D2',
  marginBottom: 5,
},
welcomeText: {
  fontSize: 14,
  color: '#424242',
  lineHeight: 20,
},
postActionsRow: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginTop: 10,
},
imageButton: {
  flexDirection: 'row',
  alignItems: 'center',
  padding: 8,
  backgroundColor: '#F5F5F5',
  borderRadius: 8,
},
submitPostButton: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#2A5B8C',
  paddingHorizontal: 16,
  paddingVertical: 8,
  borderRadius: 8,
},
submitPostButtonDisabled: {
  backgroundColor: '#CCC',
},
buttonText: {
  marginLeft: 8,
  color: '#2A5B8C',
  fontWeight: '500',
},
previewImage: {
  width: '100%',
  height: 200,
  borderRadius: 8,
  marginTop: 10,
},
postImage: {
  width: '100%',
  height: 200,
  borderRadius: 8,
  marginVertical: 10,
},
  /* Community posts */
  listContent: {
    paddingHorizontal: 15,
    paddingBottom: 20,
  },
  postCard: { 
    backgroundColor: 'white', 
    padding: 15, 
    borderRadius: 12, 
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 1,
  },
  postHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#E0E0E0',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  avatarText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#666',
  },
  postUser: { 
    fontWeight: '600', 
    color: '#333',
    fontSize: 14,
  },
  postTime: { 
    fontSize: 12, 
    color: '#999',
    marginTop: 2,
  },
  postText: { 
    fontSize: 14, 
    lineHeight: 20,
    color: '#333',
    marginBottom: 12,
  },
  incidentBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF6B6B',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  incidentBadgeText: {
    color: 'white',
    fontSize: 10,
    fontWeight: '600',
    marginLeft: 4,
  },
  postActions: { 
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
    paddingTop: 12,
  },
  actionBtn: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    marginRight: 20,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    backgroundColor: '#F8F9FA',
  },
  actionText: { 
    marginLeft: 6, 
    color: '#666',
    fontSize: 12,
    fontWeight: '500',
  },
  commentHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginBottom: 4,
  },
  commentTime: {
    fontSize: 12,
    color: '#888',
    marginTop: 4,
  },
  noComments: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  noCommentsText: {
    fontSize: 16,
    color: '#64748B',
    marginTop: 12,
  },
  noCommentsSubtext: {
    fontSize: 14,
    color: '#94A3B8',
    marginTop: 4,
  },
  commentsList: {
    flex: 1,
    padding: 16,
  },
  commentSendBtnDisabled: {
    backgroundColor: '#CBD5E1',
  },
  /* Safety Resources */
  resourceCard: {
    backgroundColor: 'white',
    padding: 15,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 1,
  },
  resourceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  resourceIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F0F7FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  resourceInfo: {
    flex: 1,
  },
  resourceLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 2,
  },
  resourceContact: {
    fontSize: 14,
    color: '#2A5B8C',
    fontWeight: '500',
  },
  resourceDescription: {
    fontSize: 12,
    color: '#666',
  },
  safetyDescription: {
    fontSize: 15,           
    color: '#4B5563',       
    marginTop: 6,
    textAlign: 'left',    
    lineHeight: 18,
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  disclaimerContainer: {
    backgroundColor: '#FFF3CD',
    borderLeftWidth: 4,
    borderLeftColor: '#FFC107',
    padding: 12,
    borderRadius: 8,
    marginTop: 15,
  },
  disclaimerText: {
    fontSize: 12,
    color: '#856404',
    lineHeight: 16,
    fontStyle: 'italic',
  },
  firstAidModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  firstAidModalContainer: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 28,
    width: '100%',
    maxHeight: '75%', 
    minHeight: 450, 
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  firstAidModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20, 
  },
  firstAidModalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#2A5B8C',
  },
  firstAidModalDivider: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginVertical: 20, 
  },
  firstAidTipContent: {
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 140, 
    paddingVertical: 15, 
    marginVertical: 15, 
  },
  firstAidTipText: {
    fontSize: 18,
    color: '#333',
    textAlign: 'center',
    lineHeight: 26,
    fontWeight: '500',
  },
  firstAidDisclaimerContainer: {
    marginTop: 20, 
    padding: 12, 
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#6B7280',
  },
  firstAidDisclaimerText: {
    fontSize: 11,
    color: '#6B7280',
    lineHeight: 15,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  firstAidModalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 25, 
    marginBottom: 10,
  },
  firstAidModalButton: {
    flex: 1,
    paddingVertical: 10, 
    borderRadius: 8, 
    alignItems: 'center',
    justifyContent: 'center',
  },
  firstAidNextTipButton: {
    backgroundColor: '#3B82F6',
  },
  firstAidGotItButton: {
    backgroundColor: '#6B7280',
  },
  firstAidNextTipText: {
    color: '#fff',
    fontSize: 14, 
    fontWeight: '600',
  },
  firstAidGotItText: {
    color: '#fff',
    fontSize: 14, 
    fontWeight: '600',
  },
  /* Neighborhood group part styling */
header: {
  backgroundColor: 'white',
  padding: 20,
  paddingBottom: 15,
  borderBottomWidth: 1,
  borderBottomColor: '#E8E8E8',
  marginBottom: 10,
},
headerTitle: {
  fontSize: 24,
  fontWeight: 'bold',
  color: '#2A5B8C',
  marginBottom: 8,
  textAlign: 'center',
},
headerSubtitle: {
  fontSize: 14,
  color: '#666',
  textAlign: 'center',
  lineHeight: 20,
  marginBottom: 15,
},
createGroupButton: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: '#2A5B8C',
  paddingHorizontal: 20,
  paddingVertical: 12,
  borderRadius: 10,
  marginHorizontal: 60,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 4,
  elevation: 3,
},
createGroupButtonText: {
  color: 'white',
  fontWeight: '600',
  fontSize: 16,
  marginLeft: 8,
},
filterSection: {
  backgroundColor: 'white',
  marginHorizontal: 15,
  marginBottom: 15,
  padding: 16,
  borderRadius: 12,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.05,
  shadowRadius: 2,
  elevation: 1,
},
filterLabel: {
  fontSize: 16,
  fontWeight: '600',
  color: '#1E293B',
  marginBottom: 10,
},
categoryScroll: {
  marginBottom: 15,
},
categoryChip: {
  paddingHorizontal: 16,
  paddingVertical: 8,
  borderRadius: 20,
  backgroundColor: '#F8FAFC',
  marginRight: 8,
  borderWidth: 1,
  borderColor: '#E2E8F0',
},
categoryChipSelected: {
  backgroundColor: '#2A5B8C',
  borderColor: '#2A5B8C',
},
categoryChipText: {
  fontSize: 12,
  fontWeight: '500',
  color: '#64748B',
},
categoryChipTextSelected: {
  color: 'white',
},
groupCard: {
  backgroundColor: 'white',
  borderRadius: 12,
  padding: 16,
  marginHorizontal: 15,
  marginBottom: 12,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.08,
  shadowRadius: 4,
  elevation: 3,
  borderLeftWidth: 4,
  borderLeftColor: '#2A5B8C',
},
groupHeader: {
  flexDirection: 'row',
  alignItems: 'flex-start',
},
groupIcon: {
  width: 44,
  height: 44,
  borderRadius: 22,
  backgroundColor: '#E3F2FD',
  justifyContent: 'center',
  alignItems: 'center',
  marginRight: 12,
},
groupContent: {
  flex: 1,
},
groupTitleRow: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'flex-start',
  marginBottom: 6,
},
groupName: {
  fontSize: 16,
  fontWeight: 'bold',
  color: '#1E293B',
  flex: 1,
  marginRight: 8,
},
categoryBadge: {
  paddingHorizontal: 8,
  paddingVertical: 4,
  borderRadius: 12,
  backgroundColor: '#F1F5F9',
},
categoryText: {
  fontSize: 10,
  fontWeight: '600',
  color: '#475569',
},
groupDescription: {
  fontSize: 14,
  color: '#4B5563',
  lineHeight: 20,
  marginBottom: 8,
},
groupStats: {
  flexDirection: 'row',
  flexWrap: 'wrap',
  gap: 12,
  marginBottom: 8,
},
stat: {
  flexDirection: 'row',
  alignItems: 'center',
},
statText: {
  fontSize: 12,
  color: '#64748B',
  marginLeft: 4,
  fontWeight: '500',
},
groupFooter: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginTop: 4,
},
createdBy: {
  fontSize: 11,
  color: '#94A3B8',
  fontStyle: 'italic',
},
groupActions: {
  flexDirection: 'row',
  gap: 8,
},
actionButton: {
  flexDirection: 'row',
  alignItems: 'center',
  paddingHorizontal: 12,
  paddingVertical: 6,
  borderRadius: 8,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.1,
  shadowRadius: 2,
  elevation: 1,
},
actionButtonText: {
  color: 'white',
  fontSize: 12,
  fontWeight: '600',
  marginLeft: 4,
},
chatButton: {
  backgroundColor: '#10B981',
},
joinButton: {
  backgroundColor: '#3B82F6',
},
leaveButton: {
  backgroundColor: '#EF4444',
},
cardTitle: {
  fontSize: 18,
  fontWeight: 'bold',
  color: '#1E293B',
  marginBottom: 12,
  marginHorizontal: 15,
},
emptyState: {
  alignItems: 'center',
  justifyContent: 'center',
  paddingVertical: 50,
  backgroundColor: 'white',
  borderRadius: 12,
  marginHorizontal: 15,
  marginTop: 10,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.05,
  shadowRadius: 2,
  elevation: 1,
},
emptyStateText: {
  fontSize: 15,
  color: '#64748B',
  textAlign: 'center',
  marginTop: 12,
  lineHeight: 20,
  paddingHorizontal: 20,
},
modalOverlay: {
  flex: 1,
  backgroundColor: 'rgba(0,0,0,0.5)',
  justifyContent: 'center',
  alignItems: 'center',
  padding: 20,
},
modalCard: {
  width: '100%',
  maxWidth: 400,
  backgroundColor: 'white',
  borderRadius: 16,
  padding: 0, 
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.2,
  shadowRadius: 8,
  elevation: 5,
  overflow: 'hidden', 
},
modalHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  paddingHorizontal: 24,
  paddingTop: 24,
  paddingBottom: 16,
  borderBottomWidth: 1,
  borderBottomColor: '#F1F5F9',
},
modalTitle: {
  fontSize: 20,
  fontWeight: 'bold',
  color: '#1E293B',
  textAlign: 'center',
  flex: 1, 
},
closeButton: {
  padding: 4,
  marginLeft: 'auto',
},
input: {
  borderWidth: 1,
  borderColor: '#E2E8F0',
  borderRadius: 10,
  padding: 16,
  fontSize: 16,
  backgroundColor: '#F8FAFC',
  marginHorizontal: 24,
  marginBottom: 16,
  marginTop: 16,
},
textArea: {
  minHeight: 80,
  textAlignVertical: 'top',
},
createGroupMainButton: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: '#2A5B8C',
  paddingHorizontal: 24,
  paddingVertical: 16,
  borderRadius: 12,
  marginHorizontal: 24,
  marginTop: 20,
  marginBottom: 24,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 4,
  elevation: 3,
},
createGroupMainButtonDisabled: {
  backgroundColor: '#CBD5E1',
  opacity: 0.6,
},
createGroupMainButtonText: {
  color: 'white',
  fontWeight: '600',
  fontSize: 16,
  marginLeft: 8,
},
button: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: '#2A5B8C',
  paddingVertical: 12,
  borderRadius: 8,
  marginTop: 8,
},
buttonDisabled: {
  backgroundColor: '#9CA3AF',
},
buttonText: {
  color: 'white',
  fontWeight: '600',
  fontSize: 16,
  marginLeft: 8,
},
chatContainer: {
  flex: 1,
  backgroundColor: '#F8FAFC',
},
chatHeader: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: 'white',
  padding: 16,
  borderBottomWidth: 1,
  borderBottomColor: '#E2E8F0',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.1,
  shadowRadius: 2,
  elevation: 2,
},
backButton: {
  padding: 8,
},
chatHeaderInfo: {
  flex: 1,
  marginLeft: 12,
},
chatGroupName: {
  fontSize: 18,
  fontWeight: 'bold',
  color: '#1E293B',
},
chatGroupStatus: {
  fontSize: 12,
  color: '#64748B',
  marginTop: 2,
},
chatHeaderButton: {
  padding: 8,
},
messagesList: {
  flex: 1,
},
messagesContent: {
  padding: 16,
},
messageBubble: {
  maxWidth: '80%',
  padding: 12,
  borderRadius: 16,
  marginBottom: 8,
},
userMessage: {
  alignSelf: 'flex-end',
  backgroundColor: '#2A5B8C',
},
otherMessage: {
  alignSelf: 'flex-start',
  backgroundColor: 'white',
  borderWidth: 1,
  borderColor: '#E2E8F0',
},
alertMessage: {
  backgroundColor: '#FEF2F2',
  borderColor: '#FECACA',
  borderWidth: 1,
},
announcementMessage: {
  backgroundColor: '#F0F9FF',
  borderColor: '#BAE6FD',
  borderWidth: 1,
},
messageUser: {
  fontSize: 12,
  fontWeight: '600',
  color: '#2A5B8C',
  marginBottom: 4,
},
messageText: {
  fontSize: 14,
  color: '#1E293B',
  lineHeight: 20,
},
userMessageText: {
  color: 'white',
},
alertMessageText: {
  color: '#DC2626',
  fontWeight: '600',
},
announcementMessageText: {
  color: '#0369A1',
  fontWeight: '500',
},
messageTime: {
  fontSize: 10,
  color: '#94A3B8',
  marginTop: 4,
  alignSelf: 'flex-end',
},
messageInputContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  padding: 16,
  backgroundColor: 'white',
  borderTopWidth: 1,
  borderTopColor: '#E2E8F0',
},
messageInput: {
  flex: 1,
  backgroundColor: '#F8FAFC',
  borderRadius: 20,
  paddingHorizontal: 16,
  paddingVertical: 12,
  marginRight: 12,
  maxHeight: 100,
  fontSize: 14,
  color: '#1E293B',
},
sendButton: {
  backgroundColor: '#2A5B8C',
  width: 40,
  height: 40,
  borderRadius: 20,
  justifyContent: 'center',
  alignItems: 'center',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.1,
  shadowRadius: 2,
  elevation: 1,
},
sendButtonDisabled: {
  backgroundColor: '#CBD5E1',
},
filterContainer: {
  flexDirection: 'row',
  marginHorizontal: 15,
  marginTop: 10,
  backgroundColor: '#F8F9FA',
  borderRadius: 8,
  padding: 4,
},
filterTab: {
  flex: 1,
  paddingVertical: 8,
  alignItems: 'center',
  borderRadius: 6,
},
filterTabActive: {
  backgroundColor: 'white',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.1,
  shadowRadius: 2,
  elevation: 2,
},
filterTabText: {
  fontSize: 14,
  fontWeight: '500',
  color: '#666',
},
filterTabTextActive: {
  color: '#2A5B8C',
  fontWeight: '600',
},
bottomModalOverlay: {
  flex: 1,
  backgroundColor: 'rgba(0,0,0,0.5)',
  justifyContent: 'flex-end',
},
bottomModalCard: {
  backgroundColor: '#fff',
  borderTopLeftRadius: 16,
  borderTopRightRadius: 16,
  padding: 20,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: -2 },
  shadowOpacity: 0.25,
  shadowRadius: 4,
  elevation: 5,
  maxHeight: '80%',
},
  /* Hamburger Menu */
  hamburgerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
  },
  hamburgerBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.3)', 
    
  },
  menuContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    pointerEvents: 'box-none', 
  },
  hamburgerMenu: {
    position: 'absolute',
    right: 0,
    top: 60,
    height: 250,
    width: 260,
    backgroundColor: 'white',
    paddingVertical: 15,
    paddingHorizontal: 20,
    zIndex: 1001,
    borderBottomLeftRadius: 20,
    borderTopLeftRadius: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: -4,
      height: 0,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
    pointerEvents: 'auto', 
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14, 
    paddingHorizontal: 12,
    borderRadius: 10, 
    marginBottom: 4,
    minHeight: 40,
  },
  menuText: {
    marginLeft: 15, 
    fontSize: 16,
    color: '#2A5B8C', 
    fontWeight: '600', 
  },
  welcomeContainer: {
    paddingBottom: 20,
    marginBottom: 10,
    marginTop: -16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  welcomeText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2A5B8C',
  },
  /* Incident report form modal */
  modalContainer: { 
    flex: 1, 
    backgroundColor: '#f8f9fa' 
  },
  modalHeader: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    padding: 15,
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  modalTitle: { 
    fontSize: 18, 
    fontWeight: '700', 
    color: '#333' 
  },
  modalContent: {
    padding: 15,
  },
  inputField: { 
    borderWidth: 1, 
    borderColor: '#E0E0E0', 
    borderRadius: 8, 
    paddingHorizontal: 12, 
    paddingVertical: 10, 
    marginBottom: 12, 
    backgroundColor: 'white',
    color: '#333',
    fontSize: 14,
  },
  
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  anonymousContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  anonymousText: {
    marginLeft: 10,
    color: '#333',
    fontSize: 14,
  },
  bottomModalOverlay: {
  flex: 1,
  backgroundColor: 'rgba(0,0,0,0.5)',
  justifyContent: 'flex-end', 
    },

    bottomModalCard: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    },
  submitButton: { 
    backgroundColor: '#2A5B8C', 
    padding: 15, 
    borderRadius: 8, 
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
  },
  submitButtonText: { 
    color: 'white', 
    fontWeight: '600',
    fontSize: 16,
  },
  typeButtonContainer: {
  flexDirection: 'row',
  flexWrap: 'wrap',
  marginVertical: 8,
  gap: 8,
},

typeButton: {
  paddingVertical: 6,
  paddingHorizontal: 12,
  backgroundColor: '#f0f0f0',
  borderRadius: 20,
  margin: 4,
},

typeButtonSelected: {
  backgroundColor: '#2A5B8C',
},

typeButtonText: {
  color: '#2A5B8C',
  fontSize: 14,
},

typeButtonTextSelected: {
  color: 'white',
},

instructionsText: {
  marginBottom: 12,
  fontSize: 14,
  color: '#333',
},

label: {
  marginTop: 10,
  marginBottom: 4,
  fontWeight: 'bold',
  color: '#2A5B8C',
},

anonymousContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  marginVertical: 12,
},

anonymousText: {
  marginLeft: 8,
  fontSize: 14,
  color: '#333',
},
hamburgerMenu: {
  position: 'absolute',
  top: 0,
  right: 0,
  height: '100%',
  width: 260,
  backgroundColor: '#fff',
  paddingTop: 60,
  paddingHorizontal: 20,
  shadowColor: '#000',
  shadowOpacity: 0.3,
  shadowOffset: { width: -2, height: 0 },
  shadowRadius: 8,
  elevation: 8,
  zIndex: 20,
},
menuItem: {
  flexDirection: 'row',
  alignItems: 'center',
  paddingVertical: 15,
  gap: 10,
},
menuText: {
  fontSize: 16,
  color: '#333',
},
//News
newsContainer: {
  alignItems: 'center',
  justifyContent: 'center',
  paddingVertical: 60,
  paddingHorizontal: 30,
},
newsPlaceholder: {
  fontSize: 18,
  fontWeight: '600',
  color: '#2A5B8C',
  textAlign: 'center',
  marginBottom: 12,
},
newsSubtext: {
  fontSize: 14,
  color: '#64748B',
  textAlign: 'center',
  lineHeight: 20,
},
});